apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../base
images:
  - name: public.ecr.aws/fsx-csi-driver/aws-fsx-csi-driver
    newName: 761018870693.dkr.ecr.us-west-2.amazonaws.com/aws-fsx-csi-driver
    newTag: v0.0.1000
